In [2]:
import pandas as pd
df = pd.read_csv(r'C:\Users\kinis\Downloads\customer_shopping_behaviour\data_1\raw_data\customer_shopping_behavior.csv')

In [10]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [3]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [ ]:
# Checks mising values using df.isnull().sum()

In [13]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [14]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [15]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [ ]:
# Convert columns name from above to all in lowercase (snake casing) so that it'll look neat & consistent

In [16]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [18]:
# Let's do some Feature Engineering
# Create a column age_group

labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [20]:
df[['age','age_group']].head(10)
#o/p- it's easier to analyze patters across diff age category, which can be really helpful marketing & for understanding customer behaviour

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [19]:
# let's create another feature->  create a purchase_frequency_days
# we'll convert this textual frequencies(weekly, annualy) into numbers, no_of_days betn purchase, this will help analysis much easier


frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 1,
    'Every 3 Months': 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [24]:
df[['purchase_frequency_days','frequency_of_purchases']].head(5)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                        1               Annually

In [32]:
#check data type of columns
print(df['discount_applied'].dtype)
print(df['promo_code_used'].dtype)

str
str

In [23]:
df[['discount_applied', 'promo_code_used']].head(5)

#Now in o/p they kind of look like same bcz if promo code was used then obv discount was applied, but sometimes businesses might
#applied discount without promo codeslike automatic seasoning sales or exclusive discount so the 
#Question is - Do we actually need both of these columns? -> let's see on next cell

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [35]:
(df['discount_applied'] == df['promo_code_used']).all()

# this gives you True for all

np.True_

In [31]:
df['discount_applied'] == df['promo_code_used']

# this checks row by row

0       True
1       True
2       True
3       True
4       True
        ...
3895    True
3896    True
3897    True
3898    True
3899    True
Length: 3900, dtype: bool

In [36]:
df = df.drop('promo_code_used', axis = 1)
#It'll drop/delete promo code column

In [37]:
#check if it is deleted or not -> yes it is deleted
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [ ]:
# Okay now we've done some Data Exploration and Data Analysis with our dataset, next step ->
#move this dataset into PostgreSQL so that we can run sql queries to do some deeper data analysis
# & ans some business questions

In [2]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in C:\Users\kinis\AppData\Roaming\Python\Python314\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in C:\Users\kinis\AppData\Roaming\Python\Python314\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in C:\Users\kinis\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\kinis\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
from sqlalchemy import create_engine
#Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details

username = "postgres"
password = "shrey23"        # the password you set during installation 
host = "localhost"            # default user #if running Locally 
port = "5432"                  # default PostgreSQL post 
database = "customer_behavior" #the database you created in pgAdmin

In [20]:
from sqlalchemy import create_engine
import pandas as pd
#Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details

username = "postgres"
password = "shrey23"        # the password you set during installation 
host = "localhost"            # default user #if running Locally 
port = "5432"                  # default PostgreSQL post 
database = "customer_behavior" #the database you created in pgAdmin

engine = create_engine (
f"postgresql+psycopg2://{username}: {password}@{host}:{port}/{database}"
)

conn = engine.connect()
print("Connect Successfully") 

#Step 2: Load DataFrame into PostgreSQL
table_name = "customer" #choose any table name

df.to_sql(
    table_name, 
    engine, 
    if_exists="replace", 
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")
#once connection is setup we can sent our dataframe into PostgreSQL

Connect Successfully
Data successfully loaded into table 'customer' in database 'customer_behavior'.